pipeline {
    agent any

    environment {
        IMAGE_NAME = "java"
        IMAGE_TAG = "latest"
        CONTAINER_NAME = "ass-java"
    }

    stages {

        stage('SCM Pull') {
            steps {
                checkout scm
            }
        }

        stage('Install Dependencies and Run Tests') {
            steps {
                sh 'mvn clean test'
            }
        }

        stage('Build') {
            steps {
                sh 'docker build -t ${IMAGE_NAME}:${IMAGE_TAG} .'
            }
        }

        stage('Deploy') {
            steps {
                sh 'docker compose down || true'
                sh 'docker compose up -d --build'
            }
        }

        stage('Curl') {
            steps {
                sh '''
                    sleep 20
                    curl -f http://localhost:8080/actuator/health
                '''
            }
        }
    }

    post {

        success {
            echo 'Application deployed successfully.'
        }

        failure {
            echo 'Pipeline failed.'
        }

        always {
            sh 'docker ps'
        }
    }
}
